---
- name: Playbook to deploy game of life project on tomcat server
  hosts: tomcat
  tasks:
  - name: Download GOL war file onto tomcat directory
    get_url: 
      url: http://35.224.65.21:8081/artifactory/gameoflife/gameoflife.war
      username: admin
      password: Maxima100%
      dest: /opt/tomcat/gameoflife.war
    become: yes
  - name: extract war file to deploy GOL application
    shell: sudo /opt/tomcat/bin/catalina.sh run /opt/tomcat/webapps/gameoflife.war
    become: yes